### ISSUE TITLE
Small build problem for xrn 10.1 using dist tarball

### ISSUE THREAD

**Issue by jschleus** [jikamens/xrn#1]
I tried to build xrn using the dist tarball downloaded from ftp://rtfm.mit.edu/pub/xrn/xrn-10.1.tar.gz. But after the usual `./configure` a subsequent `make` gave the following error:
```
rm -f mesg_str.tmp
gawk -f ./mesg_str.awk ./mesg_strings.c > mesg_str.tmp
+ cmp -s mesg_str.tmp mesg_strings.h
+ rm -f mesg_strings.h
+ mv mesg_str.tmp mesg_strings.h
make: *** No rule to make target 'xrn.spec.in', needed by 'xrn.spec'.  Stop.
```
Since the file `xrn.spec.in` wasn't available but already the target `xrn.spec` I changed testwise in the Makefile the line
```
BUILT_SOURCES = mesg_strings.h rcyacc.h xrn.spec
``` 
into
```
BUILT_SOURCES = mesg_strings.h rcyacc.h
```
and it worked. The tarball on the GitHub repository contains `xrn.spec.in` instead of `xrn.spec` and therefore isn't affected from the mentioned problem.

**Comment by jikquantopian** [comment]
Thanks for the report. Amazed that anyone is still using XRN. ;-) I've fixed this issue and pushed a new tarball.
